[package]
name = "fizzbuzz"
version = "0.1.0"
authors = ["M.-Leander Reimer <mario-leander.reimer@qaware.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
